package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 01 13:50:41 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class QueryEmployeeByEmailVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public QueryEmployeeByEmailVOImpl() {
    }
}

